services:
  - type: web
    name: vinmesse-hdg
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
