services:
  - type: web
    name: vinmesse-hdg
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1